/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiShippingRouteImport } from './routes/api/shipping'
import { Route as ApiRoutePlanRouteImport } from './routes/api/route-plan'
import { Route as ApiFlowmartOrdersRouteImport } from './routes/api/flowmart-orders'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippingRoute = ApiShippingRouteImport.update({
  id: '/api/shipping',
  path: '/api/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoutePlanRoute = ApiRoutePlanRouteImport.update({
  id: '/api/route-plan',
  path: '/api/route-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFlowmartOrdersRoute = ApiFlowmartOrdersRouteImport.update({
  id: '/api/flowmart-orders',
  path: '/api/flowmart-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flowmart-orders': typeof ApiFlowmartOrdersRoute
  '/api/route-plan': typeof ApiRoutePlanRoute
  '/api/shipping': typeof ApiShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flowmart-orders': typeof ApiFlowmartOrdersRoute
  '/api/route-plan': typeof ApiRoutePlanRoute
  '/api/shipping': typeof ApiShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/flowmart-orders': typeof ApiFlowmartOrdersRoute
  '/api/route-plan': typeof ApiRoutePlanRoute
  '/api/shipping': typeof ApiShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/flowmart-orders'
    | '/api/route-plan'
    | '/api/shipping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/flowmart-orders'
    | '/api/route-plan'
    | '/api/shipping'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/flowmart-orders'
    | '/api/route-plan'
    | '/api/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiFlowmartOrdersRoute: typeof ApiFlowmartOrdersRoute
  ApiRoutePlanRoute: typeof ApiRoutePlanRoute
  ApiShippingRoute: typeof ApiShippingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipping': {
      id: '/api/shipping'
      path: '/api/shipping'
      fullPath: '/api/shipping'
      preLoaderRoute: typeof ApiShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/route-plan': {
      id: '/api/route-plan'
      path: '/api/route-plan'
      fullPath: '/api/route-plan'
      preLoaderRoute: typeof ApiRoutePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/flowmart-orders': {
      id: '/api/flowmart-orders'
      path: '/api/flowmart-orders'
      fullPath: '/api/flowmart-orders'
      preLoaderRoute: typeof ApiFlowmartOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiFlowmartOrdersRoute: ApiFlowmartOrdersRoute,
  ApiRoutePlanRoute: ApiRoutePlanRoute,
  ApiShippingRoute: ApiShippingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
